version: '3'

services:
  minecraft-server:
    image: itzg/minecraft-server
    container_name: minecraft
    # サーバー、Dockerデーモンの再起動でマイクラサーバーも起動します。
    restart: always
    environment:
      # eula(ソフトウェア使用許諾契約)に同意します。
      - EULA=TRUE
    volumes:
      - /var/mc_data:/data
    ports:
      - 25565:25565
