version: '3'

services:
  mc:
    image: itzg/minecraft-server
    container_name: mc
    restart: always
    environment:
      - EULA=TRUE
    volumes:
      - /var/mc_data:/data
    ports:
      - 80:25565
